---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata/data/activity.zip"
download.file(fileUrl, destfile="./RepResActivity.zip")
unzip("RepResActivity.zip")
activity <- read.csv("activity.csv")
activity$date <- as.Date(activity$date, "%Y-%m-%d")
# str(activity) # just to look at the data structure
```


## What is mean total number of steps taken per day?
```{r}
# aggregating steps per day for mean and median calculation
dailysteps <- aggregate(activity$steps, by=list(Date = activity$date), sum)
colnames(dailysteps)[2] <- "sumofsteps"

hist(dailysteps$sumofsteps) # histogram of daily sum of steps
mean(dailysteps$sumofsteps, na.rm = TRUE) # mean of daily steps
median(dailysteps$sumofsteps, na.rm = TRUE) # median of daily steps
```



## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
